version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    container_name: web
    build:
      context: containers/web
      dockerfile: Dockerfile

  build:
    image: ${DOCKER_REGISTRY-}build
    container_name: build
    build:
      context: containers/build
      dockerfile: Dockerfile

  dojo:
    image: ${DOCKER_REGISTRY-}dojo
    container_name: dojo
    build:
      context: containers/dojo
      dockerfile: Dockerfile