version: '3.4'

services:
  frakas-proxy:
    image: teamhitori/frakas-proxy:<version>
    container_name: frakas-proxy

  frakas-dojo:
    image: teamhitori/frakas-dojo:<version>
    container_name: frakas-dojo

  frakas-build:
    image: teamhitori/frakas-build:<version>
    container_name: frakas-build

  frakas-web:
    image: teamhitori/frakas-web:<version>
    container_name: frakas-web
    volumes:
      - "hitorifrakasprod-id:/app/wwwroot"