version: '3.4'

services:
  frakas-proxy:
    image: ${DOCKER_REGISTRY-}frakas-proxy:220508-1754
    container_name: frakas-proxy
    build:
      context: containers/proxy
      dockerfile: Dockerfile

  frakas-web:
    image: ${DOCKER_REGISTRY-}frakas-web:220508-1754
    container_name: frakas-web
    build:
      context: containers/web
      dockerfile: Dockerfile

  frakas-build:
    image: ${DOCKER_REGISTRY-}frakas-build:220508-1754
    container_name: frakas-build
    build:
      context: containers/build
      dockerfile: Dockerfile

  frakas-dojo:
    image: ${DOCKER_REGISTRY-}frakas-dojo:220508-1754
    container_name: frakas-dojo
    build:
      context: containers/dojo
      dockerfile: Dockerfile
