#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ./containers/web/* ./containers/web
COPY ./shared/* ./shared

RUN dotnet restore "./containers/web/web.csproj"
RUN dotnet build "./containers/web/web.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./containers/web/web.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# ENTRYPOINT ["tail"]
# CMD ["-f","/dev/null"]

ENTRYPOINT ["dotnet", "web.dll"]
